name: Publish and release

on:
    pull_request:

    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository to Github workspace
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - uses: JS-DevTools/npm-publish@v1
              id: publish
              name: Publish to npm
              with:
                  token: ${{ secrets.NPM_TOKEN }}

            - if: steps.publish.outputs.type != 'none'
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.publish.outputs.version }}
                  release_name: v${{ steps.publish.outputs.version }}
                  body: v${{ steps.publish.outputs.version }}
                  draft: false
                  prerelease: false
